= jMolecules BOM

A simple BOM to ease the consumption of jMolecules JARs, especially API and Integrations JARs in combination.

== Usage

[source, xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.jmolecules</groupId>
      <artifactId>jmolecules-bom</artifactId>
      <version>2023.1.7</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
----

NOTE: Unfortunately versions defined via a BOM are not considered when declaring Maven Plugin dependency versions.
I.e. if you e.g. use the ByteBuddy integration, you will still need to declare the version explicitly.

== Released versions

[options="header"]
|===
|BOM Version|jMolecules|jMolecules Integrations
|2023.2.0-SNAPSHOT|1.10.0-SNAPSHOT|0.23.0-SNAPSHOT
|2023.1.8-SNAPSHOT|1.9.0|0.24.0-SNAPSHOT
|*2023.1.7-SNAPSHOT*|*1.9.0*|*0.23.0*
|2023.1.6|1.9.0|0.22.1
|2023.1.5|1.9.0|0.22.0
|2023.1.4|1.9.0|0.21.0
|2023.1.3|1.9.0|0.20.0
|2023.1.2|1.9.0|0.19.0
|2023.1.1|1.9.0|0.18.0
|2023.1.0|1.9.0|0.17.0
|2023.0.3-SNAPSHOT|1.8.0|0.19.0-SNAPSHOT
|2023.0.2|1.8.0|0.18.0
|2023.0.1|1.8.0|0.17.0
|2023.0.0|1.8.0|0.16.0
|2022.3.2|1.7.0|0.17.0
|2022.3.1|1.7.0|0.16.0
|2022.3.0|1.7.0|0.15.0
|2022.2.6|1.6.0|0.17.0
|2022.2.5|1.6.0|0.16.0
|2022.2.4|1.6.0|0.15.0
|2022.1.3|1.5.0|0.13.0
|2022.1.2|1.5.0|0.12.0
|2022.1.1|1.5.0|0.11.0
|2021.2.7|1.4.0|0.13.0
|2021.2.7|1.4.0|0.12.0
|2021.2.7|1.4.0|0.11.0
|===

== Version scheme

jMolecules BOM uses https://calver.org/[CalVer] with the following segment semantics:

* 202x -- the year of the release. Thus, will -- tautologically -- increase every year.
* minor digit -- a spec level. I.e. If the version of the jMolecules API JARs is increased in the release, we will bump that segment.
* bugfix digit -- the integrations level. Will be bumped if an integration release is included.
Will be reset for every release including a spec bump.

=== Example

* 2021.0.0 contained jMolecules 1.2 and jMolecules Integrations 0.2
* 2021.0.1 contained jMolecules 1.2 and jMolecules Integrations 0.3

A new release of the API JARs in 2021 will cause a BOM of 2021.1.0 to be released etc.
